engines:
  pep8:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
    - 819b6b9b70c343c117abe480c605c4b0
    - 56561c538e74ea3836139d65d34a9b45
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"
  markdownlint:
    enabled: true
    checks:
      MD001:
        enabled: false
      MD002:
        enabled: false
      MD004:
        enabled: false
      MD005:
        enabled: false
      MD006:
        enabled: false
      MD007:
        enabled: false
      MD013:
        enabled: false
      MD014:
        enabled: false
      MD022:
        enabled: false
      MD024:
        enabled: false
      MD026:
        enabled: false
      MD029:
        enabled: false
      MD031:
        enabled: false
      MD032:
        enabled: false
      MD033:
        enabled: false
      MD036:
        enabled: false
ratings:
  paths:
  - "**.py"
exclude_paths:
- logs/*
- docs/*